### ISSUE TITLE
ArgCaptor results in NullPointerException when trying to access value

### ISSUE THREAD

**Issue by michael-camacho** [mockito/mockito-scala#60] opened 2018-11-19 19:21 UTC
My code is of the form:

```
val thingsCaptor = ArgCaptor[Seq[Thing]]
verify(someMock).doStuff(thingsCaptor)
```

When I try to access the value in any way, even by doing a `toSeq`, I get a `NullPointerException`. I know that something _should_ be captured, since I can get a valid value if I use the standard Mockito `ArgumentCaptor.forClass` approach.

It's a shame, because I really like the new syntax. :)

**Comment by ultrasecreth** [comment] 2018-11-19 21:03
So I just quickly tried 
```scala
class Bar {
  def seqOfThings[T](v: Seq[T]): Int = ???
}

    "work with Seq[T]" in {
      val aMock  = mock[Bar]
      val captor = ArgCaptor[Seq[String]]

      aMock.seqOfThings(Seq("v1", "v2"))

      verify(aMock).seqOfThings(captor)

      captor.value shouldBe Seq("v1", "v2")
      captor hasCaptured Seq("v1", "v2")
    }
```

and it works, can you post a full code example? also, what version of the lib are you using?

**Comment by ultrasecreth** [comment] 2018-11-21 08:07
@michael-camacho is this still an issue?

**Comment by ultrasecreth** [comment] 2018-11-22 11:44
Can't reproduce, closing it

**Closed as completed by ultrasecreth** 2018-11-22 11:44 UTC

**Comment by michael-camacho** [comment] 2018-11-28 16:17
@bbonanno My apologies! I've not been receiving notifications for some reason. I'll have to check my settings. I only even realised you'd responded as a consequence of manually checking the issue just now. :(

I was using version 1.0.2, but the issue is still present in 1.0.5.

I hadn't tried `captor.value` before, and indeed that _does_ work and returns a `Seq` of values, but the problem I reported originally still stands -- doing `captor.toSeq` still throws a `NullPointerException`. The same thing happens if I try to leverage the implicit conversion to the captured type in other ways.

**Comment by ultrasecreth** [comment] 2018-11-28 16:21
@michael-camacho Sorry but I don't understand the problem, where would you do `captor.toSeq`? could you post a full piece of code that I can copy and paste to reproduce the issue?

**Comment by michael-camacho** [comment] 2018-11-28 17:45
@bbonanno Er, my understanding is that the new syntax supports an implicit conversion of the captor to the underlying type, so that you can use it in place of the actual value. Maybe I'm wrong though?

You would do `captor.<reallyActuallyAnySeqMethod>` anywhere after you'd captured the value. To modify your example, for instance:

```
class Bar {
  def seqOfThings[T](v: Seq[T]): Int = ???
}

"work with Seq[T]" in {
  val aMock  = mock[Bar]
  val captor = ArgCaptor[Seq[String]]

  aMock.seqOfThings(Seq("v1", "v2"))

  verify(aMock).seqOfThings(captor)

  captor.head shouldBe "v1"
}
```

In this version, `captor.head` should return the string value "v1", but instead it results in a `NullPointerException`.

**Comment by ultrasecreth** [comment] 2018-11-28 18:08
@michael-camacho The implicit conversion is from `captor` to `captor.capture`
There is no conversion between `captor` and `captor.value` as there can be only one implicit conversion `Captor[T] => T`

That's why the captor provides a convenience matcher `def hasCaptured(expectation: T)` that enables writing `captor hasCaptured Seq("v1", "v2")`

**Comment by michael-camacho** [comment] 2018-11-28 18:45
@bbonanno Ah, for the `verify`, I see! Gah, it seems obvious now. >_<

Thanks for taking the time to explain! I can see why the "problem" sounded so confusing now. I think Mockito's operation is still a bit too magical to me, and I have to spend more time looking at how it works below the surface. ;-)

**Comment by ultrasecreth** [comment] 2018-11-28 18:48
@michael-camacho No problem, happy to help!
