### ISSUE TITLE
ClassCast exception when working with captor values

### ISSUE THREAD

**Issue by ckorakidis** [mockito/mockito-scala#200] opened 2020-02-15 20:40 UTC
```
val spark = spy(SparkSession.builder().master("local[2]").appName(getClass.getSimpleName).getOrCreate())

val sessionStateSpy = spy(spark.sessionState)

Mockito.when(spark.sessionState).thenReturn(sessionStateSpy)

... do something to trigger sessionState.executePlan

verify(sessionStateSpy, Mockito.atMost(999)).executePlan(saveLogicalPlan.capture)

val inserts = vals.collect { case c: InsertIntoHadoopFsRelationCommand => c }

```

I get

```
Exception in thread "main" java.lang.ClassCastException: org.apache.spark.sql.execution.datasources.LogicalRelation cannot be cast to org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand
```

**Comment by ckorakidis** [comment] 2020-02-15 21:00
My bad, it should be `ArgCaptor[LogicalPlan]`

**Comment by ultrasecreth** [comment] 2020-02-19 09:33
@ckorakidis does that mean I can close the issue or the problem is still there?

**Comment by ultrasecreth** [comment] 2020-03-16 21:42
Closing down as it has no answers.
For future PRs, please provide examples that doesn't depend on 3rd party libraries like Spark as those are not only hard to reproduce but also hard to add to Mockito's test codebase, a clean piece of code that can be easily run is much better (and sometimes generalising the problem will actually make you solve it :) )

**Closed as completed by ultrasecreth** 2020-03-16 21:42 UTC

**Comment by ckorakidis** [comment] 2020-03-16 21:54
Apologies for the delay @bbonanno yes, thanks for replying and closing it. You know some times you investigate some issue for long and try various things and when you run out of ideas and finally decide to ask for help, the next minute you find the solution :)
